##
##  Makefile -- Build procedure for sample copyheader Apache module
##  Autogenerated via ``apxs -n copyheader -g''.
##
APXS=./apxs.sh

copyheader: mod_copyheader.so
	@echo make done
	@echo type \"make install\" to install mod_copyheader

mod_copyheader.so: mod_copyheader.c
	$(APXS) -c -n $@ mod_copyheader.c

mod_copyheader.c:

install: mod_copyheader.so
	$(APXS) -i -S LIBEXECDIR=$(DESTDIR)$$($(APXS) -q LIBEXECDIR)/ -n mod_copyheader.so mod_copyheader.la

clean:
	rm -rf *~ *.o *.so *.lo *.la *.slo *.loT .libs/
